### ISSUE TITLE
训练被截断至assert 1==2，删除后依然不可运行

### ISSUE THREAD

**Issue by Seikaijyu** [JL-er/RWKV-LORA#4]
![image](https://github.com/JL-er/RWKV-LORA/assets/68497295/66afacae-2d04-46d8-86c8-a89f74950be6)
使用如上参数会导致被截断至assert 1==2，除了PISSA训练，Lora和LISA训练尝试删除assert 1==2后依然不可运行

**Comment by JL-er** [comment]
什么报错？

**Comment by Seikaijyu** [comment]
![image](https://github.com/JL-er/RWKV-LORA/assets/68497295/83c9a724-20df-45ac-b9e4-5505b8593b9d)
Lora报错如上

**Comment by Seikaijyu** [comment]
LISA报错：
