### ISSUE TITLE
使用lisa微调RWKV 5 7B模型时报错

### ISSUE THREAD

**Issue by Seikaijyu** [JL-er/RWKV-LORA#6]
![image](https://github.com/JL-er/RWKV-LORA/assets/68497295/fb90449f-0754-48be-b3b1-08000983a054)

**Comment by Seikaijyu** [comment]
另外，RWKV6 3B模型也无法使用lisa微调，报错如下
![Uploading image.png…]()

**Comment by JL-er** [comment]
修改 --n_layer 24 --n_embd 2048
