### ISSUE TITLE
使用pissa微调的模型无法正常回复

### ISSUE THREAD

**Issue by Seikaijyu** [JL-er/RWKV-LORA#8]
![image](https://github.com/JL-er/RWKV-LORA/assets/68497295/66230349-5919-4a8e-9825-d81a5d1ca932)
![eb6ef97096d6f5aaa0b6d437de1f27f5](https://github.com/JL-er/RWKV-LORA/assets/68497295/6ead29b4-ae2a-48c6-939c-df30667cf1b1)
![512ea29cdbf74d01704dabbd66728a2f](https://github.com/JL-er/RWKV-LORA/assets/68497295/5c3fc019-68d4-4ac9-bc49-9a8b79937f7c)
![c15b536751acc4990d2c51a19237d510](https://github.com/JL-er/RWKV-LORA/assets/68497295/824b6d25-b4fb-4f40-b7c1-f4b034437d4c)
如图所示参数和效果

**Comment by Seikaijyu** [comment]
另外，合并模型后的文件尺寸有所增加，也不知道为什么
![image](https://github.com/JL-er/RWKV-LORA/assets/68497295/f7afa3b3-12df-4f2e-b094-dc1df0521515)

**Comment by Seikaijyu** [comment]
合并的模型是RWKV-x060-World-3B-v2-20240228-ctx4096.pth

**Comment by Seikaijyu** [comment]
![image](https://github.com/JL-er/RWKV-LORA/assets/68497295/3592b7d8-d1ec-442d-9401-f0059d185d35)
![image](https://github.com/JL-er/RWKV-LORA/assets/68497295/32f219de-a74c-4d77-92b3-2129280b9971)

**Comment by JL-er** [comment]
fix merge_pissa
